config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'

  resources :stories, except: [:destroy] do
    resources :comments
  end

  resources :comments do
    resources :comments
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    if user.present?
      can :create, Comment
      can :update, Comment, user_id: user.id
      can :update, Story, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :commentable, polymorphic: true, optional: true
  has_many :comments, as: :commentable

  validates_presence_of :content
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user

  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stories
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable, only: [:create]


  def create
    @commentable.comments.build(comment_params)
    if @commentable.save
      @comment = true if @commentable.try(:commentable_type)
      respond_to do |format|
        format.js
      end
    else
      byebug
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :user_id)
    end

    def set_commentable
      @commentable = Story.find(params[:story_id]) if params[:story_id]
      @commentable = Comment.find(params[:comment_id]) if params[:comment_id]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @stories = Story.all
    @story = Story.last

    fresh_when @story, last_modified: @story.updated_at
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_story, only: [:edit, :update]

  def index
  end

  def new
  end

  def create
    @story = Story.create(story_params)

    if @story.save
      redirect_to root_path, alert: 'Story created succesfully'
    else
      redirect_to root_path, alert: 'Could not save story'
    end
  end

  def show
    @story = Story.includes(:comments).order('comments.created_at DESC').find(params[:id])
  end

  def edit
  end

  def update
    @story.update(story_params)

    redirect_to @story, notice: 'Story updated successfully!'
  end

  private
    def story_params
      params.require(:story).permit(:title, :content)
    end

    def set_story
      @story = Story.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/comments/_comment.html.haml
-#- @story.comments.each do |comment|
%li= comment.content
%small.text-muted= comment.created_at.strftime("%a,%B %d, %Y at %I:%M%p")
%div
%button.link_button.add-reply Add reply

.reply.d-none
  = form_for [comment, Comment.new], remote: true do |f|
    = f.text_area :content
    = f.hidden_field :user_id, value: current_user.id
    %br
    = f.submit 'Post reply'

%hr
%div{class: "comment-comments-#{comment.id}"}
  = render 'comments/comment_comments', comment: comment

app/views/comments/_comment_comments.html.haml
%ul
  - if comment.comments
    - comment.comments.each do |comment|
      = render 'comments/comment', comment: comment

app/views/comments/create.html.haml
%h1 Comments#create
%p Find me in app/views/comments/create.html.haml

app/views/comments/create.js.haml
var commentable_id = "#{@commentable.id}"

- if @comment
  $('.comment-comments-' + commentable_id).html('');
  $('.comment-comments-' + commentable_id).append("#{j render 'comment_comments', comment: @commentable }");
- else
  $('.story-comments-section-' + commentable_id).prepend("#{j render 'comment', comment: @commentable.comments.last }")
$('textarea').val('');

app/views/home/index.html.haml
.jumbotron
  .display-4= @story.title
  %small.text-mutated= "#{time_ago_in_words(@story.created_at)} ago"
  %hr.my-4
  %p= @story.content

.row
  .col-md-7
    %p.lead Create a new story
    = form_with scope: Story.new, url: stories_path, local: true do |f|
      %p
        = f.label :title
        %br
        = f.text_field :title, class: 'form-control'
      %p
        = f.label :content
        %br
        = f.text_area :content, rows: 3, class: 'form-control'
      %p
        = f.submit 'Create Story', class: 'btn btn-success'

  .col-md-5
    %p.lead Previous stories
    - @stories.each do |story|
      %h4= story.title
      %p=  story.content
      %p= link_to 'Read more', story_path(story)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.justify-content-between.bg-light
  %a.navbar-brand{href: '/'} Storify

  %form.form-inline
    - if user_signed_in?
      =link_to 'Logout', destroy_user_session_path, method: :delete
    - else
      =link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container-fluid
      =render 'layouts/navigation'
    .container
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name}"}
          %button.close{"data-dismiss" => "alert", :type => "button"} ×
          = msg

      = yield

app/views/stories/create.html.haml
%h1 Stories#create
%p Find me in app/views/stories/create.html.haml

app/views/stories/edit.html.haml
Edit #{@story.title}
= form_with scope: @story, url: story_path, method: :put, local: true do |f|
  %p
    = f.label :title
    %br
    = f.text_field :title, class: 'form-control'
  %p
    = f.label :content
    %br
    = f.text_area :content, rows: 3, class: 'form-control'
  %p
    = f.submit 'Update Story', class: 'btn btn-success'

app/views/stories/index.html.haml
%h1 Stories#index
%p Find me in app/views/stories/index.html.haml

app/views/stories/new.html.haml
%h1 Stories#new
%p Find me in app/views/stories/new.html.haml

app/views/stories/show.html.haml
%p.display-4= @story.title
%p= @story.content

- if can? :update, @story
  = link_to 'Edit', edit_story_path(@story)

%h4 Comments
%ul{class: "story-comments-section-#{@story.id}"}
  - @story.comments.each do |comment|
    = render 'comments/comment', comment: comment

%h4 Add comment
=form_with(model: [ @story, @story.comments.build ], class: 'new_comment') do |form|
  = form.text_area :content, col: 3,class: 'form-control'
  = form.hidden_field :user_id, value: current_user.id
  %br
  = form.submit 'Add comment', class: 'btn btn-success'